### ISSUE TITLE
Option to disable OTEL exporter

### ISSUE THREAD

**Issue by sweitzel** [grafana/smtprelay#106]
Can the OTEL exporter somehow deactivated?
It is spamming the log file:

``` 
{"time":"2024-03-05T19:11:34.980755787Z","level":"ERROR","source":{"function":"github.com/grafana/smtprelay/internal/traceutil.InitTraceExporter.func1","file":"github.com/grafana/smtprelay/internal/traceutil/init.go","line":61},"msg":"OTel error","component":"trace","error":"traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:1234: connect: connection refused\""}
```

I already tried by setting some environment variables, but with no success:

```yaml
services:
  smtprelay:
    image: "grafana/smtprelay:2.0.3"
    environment:
      OTEL_SDK_DISABLED: true
      OTEL_TRACES_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_EXPORTER_OTLP_ENDPOINT: http://127.0.0.1:1234
      OTEL_EXPORTER_OTLP_TIMEOUT: 1
...
```
Only `OTEL_EXPORTER_OTLP_ENDPOINT` seems to work, but with this I was not able to disable the exporter.
